### ISSUE TITLE
Elevator ticks are off

### ISSUE THREAD

**Issue by GwhsRobotics3** [GwhsRobotics3/Team-5507-2018#17]
While testing the elevator, it went up much higher than we expected. We were testing by entering a certain number of inches but it seems like our math was wrong. But when we double checked our math, everything seemed correct. We tried looking at the number of ticks for each state and changing our code so that we would enter a number of ticks to move instead of inches, but the number of ticks changed every time we reset the position. Is there anything wrong with our code that could affect this?

public static void setDesiredPosition(double inches)
	{
		double ticks = 12*64 / (Math.PI * 1.25) * inches; 
		elevatorPulley.set(ControlMode.MotionMagic, ticks);
		
	}

**Comment by gregmarra** [comment]
One thing to consider doing is setting a relatively low target, and driving back and forth from that target to zero repeatedly. 

Does the elevator go to approximately the same position each time? If not, why not?
