### ISSUE TITLE
Autonomous modes with alliance colors

### ISSUE THREAD

**Issue by GwhsRobotics3** [GwhsRobotics3/Team-5507-2018#18]
Because we have 4 different autonomous modes, and there are 4 possibilities combinations of red/blue for the switch and scale. Would we have to make 16 different autonomous modes or is there a shorter way?

**Comment by gregmarra** [comment]
Are there parts of them that are straight up opposites of each other?

If (scale == left) then
Drive left
Else
Drive right

You could write a function that given our current alliance color (available through the FMS) and the scale/switch side (also available), returns whether left or right is the target side. Then have logic that decides what to do based on whether we are in one mode (left) or the mirror mode (right)
