### ISSUE TITLE
SmartGripper not moving while testing

### ISSUE THREAD

**Issue by GwhsRobotics3** [GwhsRobotics3/Team-5507-2018#19]
When testing our gripper, our motors are not moving not moving according to our toggles. Is there something wrong with our code or states/degrees that would affect this?

**Comment by gregmarra** [comment]
For reference, leaving the Talon software manual link here: http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf
