### ISSUE TITLE
Move Dashboard logging about Subsystems into each Subsystem

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#20]
To better organize our code, let's move the logging for each Subsystem's components into a `putExtraData()` method in the Subsystem, like we did with SmartGripper.

We should do this for SmartElevator and Intake, which currently have individual pieces of logging happening in `Robot.putSmartDashboardData()`: https://github.com/GwhsRobotics3/Team-5507-2018/blob/master/src/org/usfirst/frc/team5507/robot/Robot.java#L69

**Comment by GwhsRobotics3** [comment]
Only left on Intake
