### ISSUE TITLE
Create a SmartDashboard tab for motor information

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#22]
We should start to build our "permanent" SmartDashboard tabs. We'll want to configure a few dashboard views: one for displaying during matches, others for displaying while debugging and testing.

Let's create a SmartDashboard tab that displays motor status. For each motor, set up a list widget that contains the motor's:
* Output voltage
* Current draw
* Position as measured by encoder (for motors with these)
* Velocity as measured by encoder (for motors with these)

The Victor may not provide as much information as the Talon, so include what you can for each motor controller type. I'm not sure what information the default Talon objects in SmartDashboard give you, vs what you'll have to log yourself.

The SmartDashboard documentation suggests you can make widgets more easily grouped by naming things with a consistent prefix path (https://wpilib.screenstepslive.com/s/currentCS/m/smartdashboard/l/255411-smartdashboard-namespace):
```
SmartDashboard.putNumber("Elevator/Motor Voltage", voltage);
SmartDashboard.putNumber("Elevator/Position", position);
```

Talon SRX software manual: http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf

Prioritize these for the motors we're doing the most debugging on:
1. Gripper
2. Elevator
3. DriveTrain
4. Intake
5. Climber
6. Winch

**Comment by GwhsRobotics3** [comment]
Separate tabs created for each Subsystem
