### ISSUE TITLE
Create configTalon() method for each Subsystem

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#23]
We are starting to see that each of our Subsystems has its own needs for Talon configuration. Rather than centralizing this, let's actually break it apart for each Subsystem.

For the `DriveTrain`, `SmartElevator`, and `SmartGripper` subsystems, let's copy/paste the relevant method from https://github.com/GwhsRobotics3/Team-5507-2018/blob/master/src/org/usfirst/frc/team5507/robot/subsystems/ConfigTalon.java into the Subsystem. This way, as we're tuning the PID loops for each subsystem, or adjusting the soft limits, or other things like this, we can do it all inside the Subsystem and have that code be better organized.

**Comment by GwhsRobotics3** [comment]
Done for SmartElevator, need to do for DriveTrain
