### ISSUE TITLE
[Shuffleboard] Use LiveWindow.addChild to properly nest components inside Subsystems

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#3]
One of Shuffleboard's authors, (@SamCarlberg), has posted on Chief Delphi about how to set up Shuffleboard to show components (such as a RobotDrive or WPI_TalonSRX) inside of Subsystems to create nicely nested widgets.

https://www.chiefdelphi.com/forums/showpost.php?p=1724913&postcount=4

This will fix the issue we were seeing last weekend where these components were not nested inside of Subsystems, but loose on their own.

**Comment by GwhsRobotics3** [comment]
Wazzap Greg,
We used the LiveWindow.addChild() method from the chief delphi thread to nest things such as MecanumDrive in the Shuffleboard. Although we have not tested it yet, we will update you if the problems persist.
Thanks for the post.
Software
