### ISSUE TITLE
[Intake] Use a Limit Switch to know when to stop IntakeTakeIn

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#5]
We can use a limit switch to detect when a box is "loaded" into the intake. If we don't stop the intake wheels, we might shred the box covers, and the FRC Referees will get angry at us! If know when we're finished, we can also signal to the driver that the box is loaded, and they will know they can start to drive away even if they can't see the gripper!

A high level recipe for this:

1. Ask Mr. Hajel for a Limit Switch, and wire it up to our roadkill test board.
2. Look at this WPILib article about how to use a limit switch as a `DigitalInput` object
3. Demonstrate that you can read the value of the LimitSwitch by logging it to the dashboard
4. Use the limit switch to terminate the IntakeTakeIn command

**Comment by GwhsRobotics3** [comment]
Added a method to Intake but haven't gotten time to test it.
