### ISSUE TITLE
[Git] Remove OI.java from .gitignore

### ISSUE THREAD

**Issue by gregmarra** [GwhsRobotics3/Team-5507-2018#8]
We should figure out why we had to add OI.java to .gitignore, because it's an actual code file for the Robot that configures our controls.

Here is where it is:
https://github.com/GwhsRobotics3/Team-5507-2018/blob/b4d3e1d5e899132185e9f7b9711d5a92f322d659/.gitignore#L71

What is .gitignore?
https://git-scm.com/docs/gitignore

**Comment by gregmarra** [comment]
We might need to do this to fix issue #6

**Comment by GwhsRobotics3** [comment]
Mapped all buttons but the gitignore still has oi.java 4 times.

**Comment by GwhsRobotics3** [comment]
We directly edited the .gitignore and removed OI.java from it
